### ISSUE TITLE
jquery-mobile-rails in rails4 not working

### ISSUE THREAD

**Issue by yangxing-star** [dmarkow/jquery-mobile-rails#35]
<pre>
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    jquery-mobile-rails (>= 0) ruby depends on
      rails (~> 3.0) ruby

    rails (4.1.1)
</pre>

**Comment by dmarkow** [comment]
That's a different gem that was released 4 years ago and hasn't been updated since: http://rubygems.org/gems/jquery-mobile-rails

You want to use underscores instead: `gem 'jquery_mobile_rails'`, which will use this gem (which isn't locked to Rails 3.x).

I should probably rename this repo to avoid confusion.

**Comment by yangxing-star** [comment]
Thanks, I use jquery_mobile_rails and work very well.
